---
title: "project"
author: "Austin Banks"
date: "2024-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

### The purpose of this research is to find the correlation among tree species richness and elevation.

library(dplyr)
library(ggplot2)

tree <- readRDS("~/Documents/Biogeography/FIA_tree_master1-1.RDS")

species_richness_by_elevation <- tree %>%
  filter(!is.na(SPCD), !is.na(ELEV)) %>%
  group_by(ELEV) %>%
  summarize(species_richness = n_distinct(SPCD)) %>%
  ungroup()

species_richness_map_data <- tree %>%
  filter(!is.na(SPCD), !is.na(ELEV), !is.na(LAT), !is.na(LON)) %>%
  group_by(LAT, LON, ELEV) %>%
  summarize(species_richness = n_distinct(SPCD)) %>%
  ungroup()


ggplot(species_richness_by_elevation, aes(x = ELEV, y = species_richness)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "blue") +
  labs(title = "Species Richness vs. Elevation",
       x = "Elevation",
       y = "Species Richness") +
  theme_minimal()

ggplot(species_richness_map_data, aes(x = LON, y = LAT, color = ELEV)) +
  geom_point(alpha = 0.6, size = 1) +
  scale_color_gradient(low = "blue", high = "red") +
  labs(title = "Elevation",
       x = "Longitude",
       y = "Latitude",
       color = "Elevation") +
  theme_minimal() +
  coord_quickmap()

ggplot(species_richness_map_data, aes(x = LON, y = LAT, color = species_richness)) +
  geom_point(alpha = 0.6, size = 1) +
  scale_color_gradient(low = "blue", high = "red") +
  labs(title = "Species Richness",
       x = "Longitude",
       y = "Latitude",
       color = "Species Richness") +
  theme_minimal() +
  coord_quickmap()

species_richness_by_elevation <- species_richness_by_elevation %>%
  mutate(elevation = cut(ELEV, breaks = seq(0, 3000, by = 500), 
                             labels = c("0-500", "500-1000", "1000-1500", "1500-2000", "2000-2500", "2500-3000")))

bin_summary <- species_richness_by_elevation %>%
  group_by(elevation) %>%
  summarize(avg_species_richness = mean(species_richness), .groups = "drop")

ggplot(bin_summary, aes(x = elevation, y = avg_species_richness, fill = elevation)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Species Richness by Elevation", x = "Elevation", y = "Avg Species Richness") +
  theme_minimal()
```